<?php

declare(strict_types=1);

/**
 * @copyright Copyright (c) 2023 Felix Stupp <me+github@banananet.work>
 *
 * @license GNU AGPL version 3 or any later version
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

namespace OCA\Notifications\Devices\UnifiedPush;

use OCA\Notifications\Devices\Generic\GenericDeviceManager;
use OCP\DB\QueryBuilder\IQueryBuilder;
use OCP\IDBConnection;

class UnifiedPushDeviceManager extends GenericDeviceManager {
	public function __construct(IDBConnection $db) {
		parent::__construct($db, 'notifications_uptokens');
	}

	protected function insertDevice(UnifiedPushDevice $device): bool {
		// In case auth token is new, delete old entries with same URI by this user
		$this->deleteByUpUri(
			$device->getUID(),
			$device->getUpUri(),
		);
		return parent::insertDevice(
			$device,
		); // TODO: Change the autogenerated stub
	}

	protected function deleteByUpUri(
		string $uid,
		string $upUri,
	): bool {
		return $this->deleteByCallback(function (IQueryBuilder $query) use (
			$uid,
			$upUri,
		) {
			$query->where(
				$query->expr()->eq(
					'uid',
					$query->createNamedParameter($uid),
				),
			)->andWhere(
				$query->expr()->eq(
					'upuri',
					$query->createNamedParameter($upUri),
				),
			);
		});
	}

	protected function deviceFromRow(array $row): UnifiedPushDevice {
		return new UnifiedPushDevice(
			$row['uid'],
			$row['token'],
			$row['deviceidentifier'],
			$row['devicepublickey'],
			$row['devicepublickeyhash'],
			$row['upuri'],
			$row['apptype'],
		);
	}
}
